[package]
name = "fuzz"
version = "0.0.0"
authors = ["Alex Forster <alex@alexforster.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
pdu = { path = ".." }
honggfuzz = { version = "~0.5" }
